# Makefile for main src

all:
	$(MAKE) -C bit_print/
	$(MAKE) -C arrays/
	$(MAKE) -C structs/

clean:
	$(MAKE) -C bit_print/ clean
	$(MAKE) -C structs/ clean

cleaner:
	$(MAKE) -C bit_print/ cleaner
	$(MAKE) -C arrays/ cleaner
	$(MAKE) -C structs/ cleaner
