all: arrays arrays2 install

install:
	# Symbolically link binary into the binary folder
	ln -sf ../src/arrays/arrays ../../bin/
	ln -sf ../src/arrays/arrays2 ../../bin/

cleaner:
	rm -f arrays arrays2
